import requests
from bs4 import BeautifulSoup as bs
from collections import Counter
from requests import Session

def str2dict(data_str):
    data = {}
    for row in data_str.split('\n'):
        kv_list = row.split(":")
        data[kv_list[0]] = kv_list[1]
    return data

for i in range(1,10):
    con = Counter()
    url = "https://www.yes123.com.tw/admin/job_refer_list.asp"
    form_data = str2dict("""find_key1:軟體工程師
search_work:職務
search_multi_loc:地區
find_key2:
search_multi_loc2:請選擇地區
search_work2:請選擇職務
search_job2:請選擇行業
find_key3:
search_multi_loc3:請選擇地區
search_work3:請選擇職務
search_subj:請選擇你的科系
search_work4:
search_multi_loc4:請選擇地區
search_multi_loc5:請選擇地區
search_work6:
search_work7:
search_multi_loc6:
search_work8:
search_multi_loc7:
search_work9:請選擇職務
find_sf_subj_mode1:
s_find_sf_subj_mode1:
find_se_work_mode1:
s_find_se_work_mode1:
find_ss_work_mode1:
s_find_ss_work_mode1:
find_zone_mode1:
find_zone_mode2:
find_zone_mode3:
find_zone_mode4:
find_zone_mode5:
find_zone_mode6:
find_zone_mode7:
find_zone_mode8:
find_zone_mode9:
find_zone_mode10:
s_find_zone_mode1:
s_find_zone_mode2:
s_find_zone_mode3:
s_find_zone_mode4:
s_find_zone_mode5:
s_find_zone_mode6:
s_find_zone_mode7:
s_find_zone_mode8:
s_find_zone_mode9:
s_find_zone_mode10:
find_metro_mode1:
find_metro_mode2:
find_metro_mode3:
find_metro_mode4:
find_metro_mode5:
find_metro_mode6:
find_metro_mode7:
find_metro_mode8:
find_metro_mode9:
find_metro_mode10:
s_find_metro_mode1:
s_find_metro_mode2:
s_find_metro_mode3:
s_find_metro_mode4:
s_find_metro_mode5:
s_find_metro_mode6:
s_find_metro_mode7:
s_find_metro_mode8:
s_find_metro_mode9:
s_find_metro_mode10:
find_map_mode1:
find_map_mode2:
find_map_mode3:
find_map_mode4:
find_indy_mode1:
find_indy_mode2:
find_indy_mode3:
find_indy_mode4:
find_indy_mode5:
find_indy_mode6:
find_indy_mode7:
find_indy_mode8:
find_indy_mode9:
find_indy_mode10:
s_find_indy_mode1:
s_find_indy_mode2:
s_find_indy_mode3:
s_find_indy_mode4:
s_find_indy_mode5:
s_find_indy_mode6:
s_find_indy_mode7:
s_find_indy_mode8:
s_find_indy_mode9:
s_find_indy_mode10:
find_scl_mode1:
find_scl_mode2:
find_scl_mode3:
find_scl_mode4:
find_scl_mode5:
find_scl_mode6:
find_scl_mode7:
find_scl_mode8:
find_scl_mode9:
find_scl_mode10:
s_find_scl_mode1:
s_find_scl_mode2:
s_find_scl_mode3:
s_find_scl_mode4:
s_find_scl_mode5:
s_find_scl_mode6:
s_find_scl_mode7:
s_find_scl_mode8:
s_find_scl_mode9:
s_find_scl_mode10:
find_work_mode1:
find_work_mode2:
find_work_mode3:
find_work_mode4:
find_work_mode5:
find_work_mode6:
find_work_mode7:
find_work_mode8:
find_work_mode9:
find_work_mode10:
s_find_work_mode1:
s_find_work_mode2:
s_find_work_mode3:
s_find_work_mode4:
s_find_work_mode5:
s_find_work_mode6:
s_find_work_mode7:
s_find_work_mode8:
s_find_work_mode9:
s_find_work_mode10:
find_job_mode1:
find_job_mode2:
find_job_mode3:
find_job_mode4:
find_job_mode5:
find_job_mode6:
find_job_mode7:
find_job_mode8:
find_job_mode9:
find_job_mode10:
s_find_job_mode1:
s_find_job_mode2:
s_find_job_mode3:
s_find_job_mode4:
s_find_job_mode5:
s_find_job_mode6:
s_find_job_mode7:
s_find_job_mode8:
s_find_job_mode9:
s_find_job_mode10:
find_sche_mode1:
find_sche_mode2:
find_sche_mode3:
find_sche_mode4:
find_sche_mode5:
s_find_sche_mode1:
s_find_sche_mode2:
s_find_sche_mode3:
s_find_sche_mode4:
s_find_sche_mode5:
_mu_sf_1:
_mu_se_1:
_mu_chkbox_2:
_mu_chkbox_3:
_mu_wk_1:
_mu_wk_2:
_mu_wk_3:
_mu_wk_4:
_mu_wk_5:
_mu_job_1:
_mu_edu_1:
_mu_edu_2:
_mu_edu_3:
_mu_edu_4:
_mu_edu_5:
_mu_edu_6:
_mu_edu_7:
_mu_year_1:
_mu_year_2:
_mu_lang_1:
_mu_lang_2:
_mu_lang_3:
_mu_psn_1:
_mu_time_1:
_mu_time_2:
_mu_time_3:
_mu_time_4:
_mu_time_5:
_mu_vc_1:
_mu_vc_2:
_mu_vc_3:
_mu_vc_4:
_mu_sc_1:
_mu_sc_2:
find_subj_mode1:
find_subj_mode2:
find_subj_mode3:
s_find_subj_mode1:
s_find_subj_mode2:
s_find_subj_mode3:
find_sw_mode1:
find_sw_mode2:
find_sw_mode3:
find_sw_mode4:
find_sw_mode5:
s_find_sw_mode1:
s_find_sw_mode2:
s_find_sw_mode3:
s_find_sw_mode4:
s_find_sw_mode5:
find_cert_mode1:
find_cert_mode2:
find_cert_mode3:
find_cert_mode4:
find_cert_mode5:
s_find_cert_mode1:
s_find_cert_mode2:
s_find_cert_mode3:
s_find_cert_mode4:
s_find_cert_mode5:
find_us_sf_subj_mode1:
s_find_us_sf_subj_mode1:
find_us_se_work_mode1:
s_find_us_se_work_mode1:
find_us_work_mode1:
find_us_work_mode2:
find_us_work_mode3:
find_us_work_mode4:
find_us_work_mode5:
find_us_work_mode6:
find_us_work_mode7:
find_us_work_mode8:
find_us_work_mode9:
find_us_work_mode10:
s_find_us_work_mode1:
s_find_us_work_mode2:
s_find_us_work_mode3:
s_find_us_work_mode4:
s_find_us_work_mode5:
s_find_us_work_mode6:
s_find_us_work_mode7:
s_find_us_work_mode8:
s_find_us_work_mode9:
s_find_us_work_mode10:
find_us_zone_mode1:
find_us_zone_mode2:
find_us_zone_mode3:
find_us_zone_mode4:
find_us_zone_mode5:
find_us_zone_mode6:
find_us_zone_mode7:
find_us_zone_mode8:
find_us_zone_mode9:
find_us_zone_mode10:
s_find_us_zone_mode1:
s_find_us_zone_mode2:
s_find_us_zone_mode3:
s_find_us_zone_mode4:
s_find_us_zone_mode5:
s_find_us_zone_mode6:
s_find_us_zone_mode7:
s_find_us_zone_mode8:
s_find_us_zone_mode9:
s_find_us_zone_mode10:
find_us_metro_mode1:
find_us_metro_mode2:
find_us_metro_mode3:
find_us_metro_mode4:
find_us_metro_mode5:
find_us_metro_mode6:
find_us_metro_mode7:
find_us_metro_mode8:
find_us_metro_mode9:
find_us_metro_mode10:
s_find_us_metro_mode1:
s_find_us_metro_mode2:
s_find_us_metro_mode3:
s_find_us_metro_mode4:
s_find_us_metro_mode5:
s_find_us_metro_mode6:
s_find_us_metro_mode7:
s_find_us_metro_mode8:
s_find_us_metro_mode9:
s_find_us_metro_mode10:
find_us_indy_mode1:
find_us_indy_mode2:
find_us_indy_mode3:
find_us_indy_mode4:
find_us_indy_mode5:
find_us_indy_mode6:
find_us_indy_mode7:
find_us_indy_mode8:
find_us_indy_mode9:
find_us_indy_mode10:
s_find_us_indy_mode1:
s_find_us_indy_mode2:
s_find_us_indy_mode3:
s_find_us_indy_mode4:
s_find_us_indy_mode5:
s_find_us_indy_mode6:
s_find_us_indy_mode7:
s_find_us_indy_mode8:
s_find_us_indy_mode9:
s_find_us_indy_mode10:
find_us_map_mode1:
find_us_map_mode2:
find_us_map_mode3:
find_us_map_mode4:
strrec:0
search_key_word:軟體工程師
search_type:job
us_menu:
search_item:1
search_from:index""")

res = requests.post(url,data=form_data)
res.encoding = "utf8"
soup = bs (res.text,"lxml")

for job in soup.select("a.jobname"):
    hr = job['href']
    jb1 = hr.split('p_id=')[1].split('&job_id=')[0]
#     print(jb1)
    jb2 = hr.split('&job_id=')[1]
#     print(jb2)
    res2 = requests.get("https://www.yes123.com.tw/admin/job_refer_comp_job_detail2.asp?p_id="+jb1+"&job_id="+jb2)
    soup2 = bs(res2.text,'lxml')
    data = soup2.select('.rr')
    print(data)
    print('-' * 50)
    # print([field for field in soup2.select('.rr') if "程式設計：" in field.text])
    # print('-'*50)
